[package]
name = "codechain_informer_courier"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
